name: Update Releases File

on:
  release:
    types: [published]
    
jobs:
  update_release_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get All Release Names
        id: get_release_names
        run: |
          ALL_RELEASES=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/releases")

          RELEASE_NAMES=$(echo "$ALL_RELEASES" | jq -r '.[].name | select(.)')
          echo "release_names=$RELEASE_NAMES" >> $GITHUB_OUTPUT

      - name: Create or Update release_names.txt
        run: |
          echo "${{ steps.get_release_names.outputs.release_names }}" > release_names.txt

      - name: Commit and Push to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: "Update release_names.txt for new release"
          file_pattern: "release_names.txt"
