name: Update Release Names on GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update_release_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      # COMBINED and CORRECTED step
      - name: Fetch release names and write to file
        run: |
          curl -s -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases" | \
            jq -r '.[].name | select(.)' > release_names.txt

      - name: Commit and Push to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: "Update release_names.txt"
          file_pattern: "release_names.txt"
